version: "3.9"
services:
  rabbitMQ:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "8080:15672"
    env_file:
      - ./configs/mq.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
  chatbot:
    build: .
    depends_on:
      - rabbitMQ
    restart: on-failure
    ports:
      - "8081:5000"
    env_file:
      - ./configs/api.env
  chat:
    build: ./src/chatbot
    depends_on:
      - rabbitMQ
    ports:
      - "80:80"
  worker:
    build: ./src/finance-bot.Worker
    restart: on-failure
    depends_on:
      - rabbitMQ
    env_file:
      - ./configs/worker.env
